<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13786" started-at="2018-12-10T16:14:13Z" finished-at="2018-12-10T16:14:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13786" started-at="2018-12-10T16:14:13Z" finished-at="2018-12-10T16:14:27Z">
      <class name="com.bl.base.Base">
        <test-method status="FAIL" signature="beforeClass()[pri:0, instance:com.bl.base.Base@1e397ed7]" name="beforeClass" duration-ms="11493" started-at="2018-12-10T16:14:13Z" finished-at="2018-12-10T16:14:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.bl.base.Base.beforeClass(Base.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
      </class> <!-- com.bl.base.Base -->
      <class name="com.bl.api.ApiResponse">
        <test-method status="PASS" signature="zillowResponce()[pri:1, instance:com.bl.api.ApiResponse@490ab905]" name="zillowResponce" duration-ms="2240" started-at="2018-12-10T16:14:25Z" finished-at="2018-12-10T16:14:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- zillowResponce -->
      </class> <!-- com.bl.api.ApiResponse -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
